language: java
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
 email: false

before_install:
 - chmod +x gradlew

script: AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" AWS_SECRET_KEY="$AWS_SECRET_KEY" mvn clean install -e beanstalk:upload-source-bundle beanstalk:create-application-version beanstalk:update-environment

after_success:
- ./gradlew cobertura pitest coveralls
